# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43ef246df0a70070ce2302444ecf7d85f2be32eac9214706684d517d1489d021f5df0b97dc0694534cf1a627891e9fe621fae84d1695a79be9adf63c94891cb3

test:
  secret_key_base: 66471b8d18a8a20a7efdc8c8a0583398cec12db4ceadddda8a393c899baabf16a98145dc3876d60e431e474089c5f3f34fdd4ab445747897e8fccf2c01890581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
